#!/bin/bash

set -euxo pipefail

readonly IMAGE_NAMESPACE='iluvzhouying'
readonly IMAGE_NAME='shift-scheduler-api'
readonly GIT_COMMIT_SHORT=$(git log -1 --pretty=%h)
readonly IMAGE="${IMAGE_NAMESPACE}/${IMAGE_NAME}:${GIT_COMMIT_SHORT}"

npm test 

docker build -t ${IMAGE} . 

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 

docker push ${IMAGE}